services:
  mongodb:
    image: mongo:7.0
    command: ["--replSet", "rs0", "--bind_ip_all"]
    volumes:
      - './volumes/mongo/db:/data/db'
      - './volumes/mongo/configdb:/data/configdb'
    healthcheck:
      test: echo "try { rs.status() } catch (err) { rs.initiate({_id:'rs0',members:[{_id:0,host:'mongodb:27017'}]}) }" | mongosh --port 27017 --quiet
      start_period: 10s
      start_interval: 1s

  privmx-pki-server:
    image: 'simplito/privmx-pki-server'
    environment:
      - PMX_HOST=0.0.0.0
      - PMX_MONGO_URL=mongodb://mongodb/
      - PMX_CORS_ENABLED=true
      - PMX_CORS_ORIGINS=*

    volumes:
      - './:/app'
    ports:
      - "8101:8101"
    depends_on:
      - mongodb

